// Generated by gencpp from file cpg_hopf_control_1/msg_jointangle.msg
// DO NOT EDIT!


#ifndef CPG_HOPF_CONTROL_1_MESSAGE_MSG_JOINTANGLE_H
#define CPG_HOPF_CONTROL_1_MESSAGE_MSG_JOINTANGLE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace cpg_hopf_control_1
{
template <class ContainerAllocator>
struct msg_jointangle_
{
  typedef msg_jointangle_<ContainerAllocator> Type;

  msg_jointangle_()
    : stamp()
    , jointangle()  {
      jointangle.assign(0.0);
  }
  msg_jointangle_(const ContainerAllocator& _alloc)
    : stamp()
    , jointangle()  {
  (void)_alloc;
      jointangle.assign(0.0);
  }



   typedef ros::Time _stamp_type;
  _stamp_type stamp;

   typedef boost::array<double, 20>  _jointangle_type;
  _jointangle_type jointangle;





  typedef boost::shared_ptr< ::cpg_hopf_control_1::msg_jointangle_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::cpg_hopf_control_1::msg_jointangle_<ContainerAllocator> const> ConstPtr;

}; // struct msg_jointangle_

typedef ::cpg_hopf_control_1::msg_jointangle_<std::allocator<void> > msg_jointangle;

typedef boost::shared_ptr< ::cpg_hopf_control_1::msg_jointangle > msg_jointanglePtr;
typedef boost::shared_ptr< ::cpg_hopf_control_1::msg_jointangle const> msg_jointangleConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::cpg_hopf_control_1::msg_jointangle_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::cpg_hopf_control_1::msg_jointangle_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace cpg_hopf_control_1

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'cpg_hopf_control_1': ['/home/apengse/APengse/Ros/ros_snake_like_robot/src/cpg_hopf_control_1/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::cpg_hopf_control_1::msg_jointangle_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::cpg_hopf_control_1::msg_jointangle_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::cpg_hopf_control_1::msg_jointangle_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::cpg_hopf_control_1::msg_jointangle_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cpg_hopf_control_1::msg_jointangle_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cpg_hopf_control_1::msg_jointangle_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::cpg_hopf_control_1::msg_jointangle_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c599ebcef0cb4213f6d5e44ba736a1ea";
  }

  static const char* value(const ::cpg_hopf_control_1::msg_jointangle_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc599ebcef0cb4213ULL;
  static const uint64_t static_value2 = 0xf6d5e44ba736a1eaULL;
};

template<class ContainerAllocator>
struct DataType< ::cpg_hopf_control_1::msg_jointangle_<ContainerAllocator> >
{
  static const char* value()
  {
    return "cpg_hopf_control_1/msg_jointangle";
  }

  static const char* value(const ::cpg_hopf_control_1::msg_jointangle_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::cpg_hopf_control_1::msg_jointangle_<ContainerAllocator> >
{
  static const char* value()
  {
    return "time stamp\n\
float64[20] jointangle\n\
";
  }

  static const char* value(const ::cpg_hopf_control_1::msg_jointangle_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::cpg_hopf_control_1::msg_jointangle_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.stamp);
      stream.next(m.jointangle);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct msg_jointangle_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::cpg_hopf_control_1::msg_jointangle_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::cpg_hopf_control_1::msg_jointangle_<ContainerAllocator>& v)
  {
    s << indent << "stamp: ";
    Printer<ros::Time>::stream(s, indent + "  ", v.stamp);
    s << indent << "jointangle[]" << std::endl;
    for (size_t i = 0; i < v.jointangle.size(); ++i)
    {
      s << indent << "  jointangle[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.jointangle[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // CPG_HOPF_CONTROL_1_MESSAGE_MSG_JOINTANGLE_H
